name: Build and Release APK

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19'  # Adjust to your Flutter version
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi
      - name: Release on GitHub 
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ github.run_number }} # Use a tag format appropriate for your project
      - name: Upload assets to Github Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create-new-release.outputs.upload_url}}
          asset_path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          asset_name: ToolBox-arm64-v8a-${{github.run_number}}.apk
          asset_content_type: application/apk
      - name: Print Upload URL for reference
        run: echo "https://api.telegram.org/bot${{ vars.TELEGRAM_BOT_TOKEN }}/sendDocument"
      - name: Send build files to telegram 
        run: |
          curl -F "document=build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" \
               -F "chat_id=${{ vars.TELEGRAM_BOT_PERSONAL_CHAT_ID }}" \
               -F "caption=ToolBox arm64 build:${{github.run_number}}" \
               -X POST https://api.telegram.org/bot${{ vars.TELEGRAM_BOT_TOKEN }}/sendDocument
      - name: Send build files to telegram 
        run: |
          curl -F "document=build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk" \
               -F "chat_id=${{ vars.TELEGRAM_BOT_PERSONAL_CHAT_ID }}" \
               -F "caption=ToolBox arm build:${{github.run_number}}" \
               -X POST https://api.telegram.org/bot${{ vars.TELEGRAM_BOT_TOKEN }}/sendDocument